### ISSUE TITLE
Using the search bar results in a 404

### ISSUE THREAD

**Issue by ghost** [phntxx/dashboard#61]
Really liking the dashboard! Everything is great except I'm unable to get the search bar working with or without the prefixes. Upon searching, it will immediately result in 404 Not Found, nginx. 

The URL also changes to /undefinedsearch

The search providers .json is the same as the one in the repo.

**Comment by phntxx** [comment]
Hi!

I just realized that this is due to a change i made in the `search.json` file.

Previously, the file was structured like this:

```json
{
  "search": {
    "defaultProvider": "...",
    "providers": {
      ...
    }
  }
}
```

The method that reads the contents of this file now expects the file to be formatted like this:

```json
{
  "defaultProvider": "...",
  "providers": {
    ...
  }
}
```

I am terribly sorry for the inconvenience and will try to communicate such changes better in the future.

Kind regards
phntxx
